import Provider from '@/components/ThemeProvider'
import '@/styles/tailwind.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <Provider>{children}</Provider>
}
